# Generated by Django 3.2.5 on 2022-03-28 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('month_count', models.BigIntegerField(blank=True, null=True, verbose_name='Month Count')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Salary')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.class', verbose_name='Class')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Last Name')),
                ('phone_number', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Phone Number')),
                ('fb_link', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Facebook Profile')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='main.course', verbose_name='Course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=30, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Last Name')),
                ('phone_number', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Phone Number')),
                ('fb_link', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Facebook Profile')),
                ('discord_username', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Discord Nickname')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.parent', verbose_name='Parent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')], default=1)),
                ('lesson_time', models.TimeField(default='12:00', verbose_name='Time')),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, '0:15'), (30, '0:30'), (45, '0:45'), (60, '1:00'), (75, '1:15'), (90, '1:30'), (105, '1:45'), (120, '2:00'), (135, '2:15'), (150, '2:30')], default=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.class', verbose_name='Class')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.student', verbose_name='Student')),
                ('time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.time', verbose_name='Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='main.Student', verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
