# Generated by Django 3.2.5 on 2022-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Register Code',
                'verbose_name_plural': 'Register Codes',
            },
        ),
    ]
